// Generated by CoffeeScript 1.6.2
(function() {
  " Wrapper for an ACE code editor. ";  window.CodeEditor = (function() {
    function CodeEditor(aceEditor) {
      this.aceEditor = aceEditor;
      this.aceEditor.setTheme("ace/theme/tomorrow_night_eighties");
      this.aceEditor.getSession().setMode("ace/mode/html");
      this.aceEditor.setFontSize("16px");
    }

    CodeEditor.prototype.setCodeContents = function(code) {
      this.aceEditor.setValue(code);
      return this.aceEditor.navigateFileStart();
    };

    CodeEditor.prototype.getCodeContents = function() {
      return this.aceEditor.getValue();
    };

    return CodeEditor;

  })();

}).call(this);
