// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.FileHandler = (function() {
    function FileHandler(output) {
      this.output = output;
      this.handleDrop = __bind(this.handleDrop, this);
    }

    FileHandler.prototype.handleDrop = function(event) {
      var droppedFiles, file, reader,
        _this = this;

      console.log("Drop event");
      console.log(event);
      droppedFiles = event.originalEvent.dataTransfer.files;
      console.log(droppedFiles);
      if (droppedFiles.length > 1) {
        console.error("Only handling one file for now.");
      }
      file = droppedFiles[0];
      console.log("processing " + file.name);
      reader = new FileReader();
      console.log(reader);
      reader.readAsText(file);
      return reader.onload = function(evt) {
        var text;

        console.log("reader loaded");
        text = evt.target.result;
        console.log(text);
        return _this.output.val(text);
      };
    };

    return FileHandler;

  })();

}).call(this);
