// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    var webRTC,
      _this = this;

    console.log("Initializing global state");
    window.fileStore = new FileStore();
    webRTC = new WebRTC(window.fileStore, $("#user-portal"));
    $("#file-drop").bind('drop dragover', function(e) {
      return e.preventDefault();
    });
    window.drop_handler = new DropHandler(window.fileStore, $("#file-list"), editor);
    $("#file-drop").bind("drop", window.drop_handler.handleDrop);
    $("#send-content").click(function() {
      return webRTC.sendEvent("textAreaValueChanged", editor.getCodeContents());
    });
    editor.setCodeContents("<!-- Code goes here -->");
    return $("#file-list").change(function() {
      var selected_file;

      selected_file = $("#file-list option:selected").val();
      return editor.setCodeContents(window.fileStore.getFileContents(selected_file));
    });
  });

}).call(this);
