// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PathMappingCollectionView = (function(_super) {
    __extends(PathMappingCollectionView, _super);

    function PathMappingCollectionView() {
      _ref = PathMappingCollectionView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PathMappingCollectionView.prototype.el = "#path-mapping-collection-view";

    PathMappingCollectionView.prototype.initialize = function() {
      _.bindAll(this);
      this.collection = new PathMappingCollection();
      this.collection.bind("add", this.appendPathMapping);
      this.uninitializedPathMappingView = null;
      return this.render();
    };

    PathMappingCollectionView.prototype.render = function() {
      $(this.el).html("<ul class=\"nav nav-tabs\">\n  <li class=\"add-button-li\"><a href=\"#\"><i>+ Add Path Mapping</i></a></li>\n</ul>\n\n<div class=\"tab-content\"></div>");
      return this;
    };

    PathMappingCollectionView.prototype.addPathMapping = function() {
      var pathMapping;

      pathMapping = new PathMapping();
      return this.collection.add(pathMapping);
    };

    PathMappingCollectionView.prototype.appendPathMapping = function(pathMapping) {
      var navTabEl;

      this.uninitializedPathMappingView = new PathMappingView({
        model: pathMapping
      });
      $(".nav-tabs li").removeClass("active");
      $(".tab-pane").removeClass("active");
      navTabEl = $("<li class='active'>\n  <input type=\"text\" placeholder=\"Type something…\">\n</li>");
      navTabEl.find("a").tab("show");
      $(".add-button-li").before(navTabEl);
      return navTabEl.find("input").focus();
    };

    PathMappingCollectionView.prototype.handleNavTabInputBlur = function(event) {
      var input, path;

      input = $(event.target);
      this.uninitializedPathMappingView.model.set("path", input.val());
      path = this.uninitializedPathMappingView.model.get("path");
      input.replaceWith("<a data-toggle='tab' href='#" + path + "'>" + path + "</a>");
      $(".tab-content").append(this.uninitializedPathMappingView.render().el);
      return this.uninitializedPathMappingView = null;
    };

    PathMappingCollectionView.prototype.events = {
      "click .add-button-li a": "addPathMapping",
      "blur .nav-tabs input": "handleNavTabInputBlur"
    };

    return PathMappingCollectionView;

  })(Backbone.View);

}).call(this);
