// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PathMappingView = (function(_super) {
    __extends(PathMappingView, _super);

    function PathMappingView() {
      this.render = __bind(this.render, this);      _ref = PathMappingView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PathMappingView.prototype.className = "tab-pane active";

    PathMappingView.prototype.initialize = function() {
      return _.bindAll(this);
    };

    PathMappingView.prototype.render = function() {
      var template;

      this.el.id = this.model.get("path");
      template = Handlebars.compile($("#tab-pane-template").html());
      $(this.el).html(template);
      new CodeEditor(ace.edit($(this.el).find(".file-contents")));
      return this;
    };

    return PathMappingView;

  })(Backbone.View);

}).call(this);
