// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PathMapping = (function(_super) {
    __extends(PathMapping, _super);

    function PathMapping() {
      _ref = PathMapping.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PathMapping.prototype.defaults = {
      path: "index",
      files: ["page.html", "style.css", "image.png"]
    };

    return PathMapping;

  })(Backbone.Model);

}).call(this);
