// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.ClientDataChannel = (function() {

    function ClientDataChannel(onDataCallback) {
      var _this = this;
      this.onDataCallback = onDataCallback;
      this.onData = function(data) {
        return ClientDataChannel.prototype.onData.apply(_this, arguments);
      };
      this.onOpen = function(id) {
        return ClientDataChannel.prototype.onOpen.apply(_this, arguments);
      };
      if (isDevelopmentServer()) {
        this.peer = new Peer({
          host: location.hostname,
          port: 9000,
          config: {
            'iceServers': []
          }
        });
      } else {
        this.peer = new Peer({
          key: "rrvwvw4tuyxpqfr",
          config: {
            "iceServers": []
          }
        });
      }
      this.peer.on("open", this.onOpen);
    }

    ClientDataChannel.prototype.onOpen = function(id) {
      return this.id = id;
    };

    ClientDataChannel.prototype.onData = function(data) {
      return this.onDataCallback(data);
    };

    return ClientDataChannel;

  })();

}).call(this);
