// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.ClientDataChannel = (function() {
    function ClientDataChannel(onConnectionCallback, onMessageCallback) {
      this.onConnectionCallback = onConnectionCallback;
      this.onMessageCallback = onMessageCallback;
      this.onData = __bind(this.onData, this);
      this.onConnection = __bind(this.onConnection, this);
      this.onOpen = __bind(this.onOpen, this);
      this.peer = new Peer({
        key: 'rrvwvw4tuyxpqfr'
      });
      this.peer.on("open", this.onOpen);
      this.peer.on("connection", this.onConnection);
    }

    ClientDataChannel.prototype.onOpen = function(id) {
      this.id = id;
      return this.dataChannelReady();
    };

    ClientDataChannel.prototype.onConnection = function(connection) {
      var _this = this;

      connection.on("open", function() {
        return _this.onConnectionCallback(connection);
      });
      return connection.on("data", function(data) {
        return _this.onData(connection, data);
      });
    };

    ClientDataChannel.prototype.onData = function(connection, data) {
      console.log(connection, data);
      return this.onMessageCallback(connection, data);
    };

    return ClientDataChannel;

  })();

}).call(this);

/*
//@ sourceMappingURL=ClientDataChannel.map
*/
