// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.EventTransmitter = (function() {
    function EventTransmitter() {
      this.receiveEvent = __bind(this.receiveEvent, this);
      this.sendEvent = __bind(this.sendEvent, this);
      this.addEventCallback = __bind(this.addEventCallback, this);      this.eventCallbacks = {};
    }

    EventTransmitter.prototype.addEventCallback = function(eventName, callback) {
      var eventCallbacks;

      eventCallbacks = this.eventCallbacks[eventName];
      if (!eventCallbacks) {
        eventCallbacks = [];
      }
      eventCallbacks.push(callback);
      return this.eventCallbacks[eventName] = eventCallbacks;
    };

    EventTransmitter.prototype.sendEvent = function(dataChannel, eventName, data) {
      console.log("send event " + eventName);
      return dataChannel.send(JSON.stringify({
        "eventName": eventName,
        "data": data
      }));
    };

    EventTransmitter.prototype.receiveEvent = function(messageEventData) {
      var eventCallback, eventCallbacks, eventName, messageData, _i, _len, _results;

      messageEventData = JSON.parse(messageEventData);
      eventName = messageEventData.eventName;
      messageData = messageEventData.data;
      console.log("receive event " + eventName, messageData);
      eventCallbacks = this.eventCallbacks[eventName];
      if (eventCallbacks) {
        _results = [];
        for (_i = 0, _len = eventCallbacks.length; _i < _len; _i++) {
          eventCallback = eventCallbacks[_i];
          _results.push(eventCallback(messageData));
        }
        return _results;
      }
    };

    return EventTransmitter;

  })();

}).call(this);
