// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this;

  window.FakeAjax = (function() {

    function FakeAjax() {
      var _this = this;
      this.jqAjax = function(path, options) {
        return FakeAjax.prototype.jqAjax.apply(_this, arguments);
      };
    }

    FakeAjax.prototype.jqAjax = function(path, options) {
      if ("success" in options) {
        this.success = options["success"];
      }
      if ("failure" in options) {
        this.failure = options["failure"];
      }
      console.log("success is now:" + this.success);
      return top.window.webRTC.ajaxClient.requestAjax(path, this.success);
    };

    return FakeAjax;

  })();

  $.ajax = function(url, options) {
    var fajax;
    fajax = new FakeAjax();
    return fajax.jqAjax(url, options);
  };

}).call(this);
