// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ClientBrowserDataChannel = (function(_super) {

    __extends(ClientBrowserDataChannel, _super);

    function ClientBrowserDataChannel() {
      this.parseUrl = __bind(this.parseUrl, this);

      this.onFileReceived = __bind(this.onFileReceived, this);

      this.onFileSent = __bind(this.onFileSent, this);

      this.onFileProgress = __bind(this.onFileProgress, this);

      this.onOpen = __bind(this.onOpen, this);

      this.onMessage = __bind(this.onMessage, this);

      this.openSignalingChannel = __bind(this.openSignalingChannel, this);

      this.initDataChannel = __bind(this.initDataChannel, this);

      this.handleSetID = __bind(this.handleSetID, this);

      var startPage, _ref;
      _ref = this.parseUrl(window.location.pathname), this.desiredServer = _ref[0], startPage = _ref[1];
      this.dataChannel = new DataChannel();
      this.socket = io.connect(document.location.origin);
      this.socket.on("setID", this.handleSetID);
    }

    ClientBrowserDataChannel.prototype.handleSetID = function(id) {
      this.id = id;
      this.initDataChannel();
      return this.dataChannel.connect(this.desiredServer);
    };

    ClientBrowserDataChannel.prototype.initDataChannel = function() {
      this.dataChannel.openSignalingChannel = this.openSignalingChannel;
      this.dataChannel.onmessage = this.onMessage;
      this.dataChannel.onopen = this.onOpen;
      this.dataChannel.onFileProgress = this.onFileProgress;
      this.dataChannel.onFileSent = this.onFileSent;
      return this.dataChannel.onFileReceived = this.onFileReceived;
    };

    ClientBrowserDataChannel.prototype.openSignalingChannel = function(config) {
      var channel, channelSocket, sender;
      channel = config.channel || this.dataChannel.channel;
      sender = this.id;
      io.connect(document.location.origin).emit("newDataChannel", {
        channel: channel,
        sender: sender
      });
      channelSocket = io.connect(document.location.origin + "/" + channel);
      channelSocket.channel = channel;
      channelSocket.on("connect", function() {
        if (config.callback) {
          return config.callback(channelSocket);
        }
      });
      channelSocket.send = function(message) {
        console.log("send", {
          sender: sender,
          data: message
        });
        return channelSocket.emit("message", {
          sender: sender,
          data: message
        });
      };
      return channelSocket.on("message", config.onmessage);
    };

    ClientBrowserDataChannel.prototype.onMessage = function(data) {
      return console.log(data);
    };

    ClientBrowserDataChannel.prototype.onOpen = function() {
      console.log("onopen");
      return this.dataChannel.send("CLIENT: " + this.id);
    };

    ClientBrowserDataChannel.prototype.onFileProgress = function() {};

    ClientBrowserDataChannel.prototype.onFileSent = function() {};

    ClientBrowserDataChannel.prototype.onFileReceived = function() {};

    ClientBrowserDataChannel.prototype.parseUrl = function(pathname) {
      var serverId, slashIndex, startPage, suffix;
      if (pathname.indexOf("connect") === -1) {
        console.error("Error: pathname does not contain 'connect'");
      }
      suffix = pathname.substr("/connect/".length);
      slashIndex = suffix.indexOf("/");
      startPage = null;
      if (slashIndex !== -1) {
        serverId = suffix.substr(0, slashIndex);
        if (slashIndex !== (suffix.length - 1)) {
          startPage = suffix.substr(suffix.indexOf("/") + 1);
        }
      } else {
        serverId = suffix;
      }
      return [serverId, startPage];
    };

    return ClientBrowserDataChannel;

  })(DataChannel);

}).call(this);
