// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ClientBrowserDataChannel = (function(_super) {
    __extends(ClientBrowserDataChannel, _super);

    function ClientBrowserDataChannel(onOpenCallback, onMessageCallback, desiredServer) {
      this.onOpenCallback = onOpenCallback;
      this.onMessageCallback = onMessageCallback;
      this.desiredServer = desiredServer;
      this.dataChannelReady = __bind(this.dataChannelReady, this);
      ClientBrowserDataChannel.__super__.constructor.call(this, this.onOpenCallback, this.onMessageCallback);
    }

    ClientBrowserDataChannel.prototype.dataChannelReady = function() {
      return this.dataChannel.connect(this.desiredServer);
    };

    return ClientBrowserDataChannel;

  })(ClientDataChannel);

}).call(this);
