// Generated by CoffeeScript 1.3.3
(function() {

  $(document).ready(function() {
    var _this = this;
    document.getElementById("container").contentWindow.document.location.href = "/client/entryframe.html";
    document.getElementById("container").onload = function(evt) {
      return window.clientBrowser = new ClientBrowser(document.getElementById("container").contentWindow.document.documentElement);
    };
    return $(document).on("relativeLinkClicked", function(evt, href) {
      console.log("REQUESTING FILE " + href + "....");
      return window.clientBrowser.htmlProcessor.requestFile(href, "alink");
    });
  });

}).call(this);
