// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.WebRTC = (function() {
    function WebRTC() {
      this.sendEvent = __bind(this.sendEvent, this);
      this.receiveOffer = __bind(this.receiveOffer, this);
      var _this = this;

      this.peerConnections = {};
      this.connection = io.connect("http://localhost:8890");
      this.connection.emit('joinAsServer');
      this.connection.on('joined', function(clientID) {
        _this.addPeerConnection(clientID);
        return console.log('client joined', clientID);
      });
      this.connection.on("receiveOffer", this.receiveOffer);
      this.dataChannels = {};
      this.dataChannelConfig = {
        "optional": [
          {
            "RtpDataChannels": true
          }
        ]
      };
    }

    WebRTC.prototype.addPeerConnection = function(clientID) {
      var pc,
        _this = this;

      pc = new RTCPeerConnection(null, this.dataChannelConfig);
      this.peerConnections[clientID] = pc;
      pc.ondatachannel = function(evt) {
        console.log('data channel connecting ' + clientID);
        _this.addDataChannel(clientID, evt.channel);
      };
    };

    WebRTC.prototype.receiveOffer = function(clientID, sdp) {
      var pc;

      pc = this.peerConnections[clientID];
      pc.setRemoteDescription(new RTCSessionDescription(sdp));
    };

    WebRTC.prototype.addDataChannel = function(clientID, channel) {
      var _this = this;

      console.log("adding data channel");
      channel.onopen = function() {
        return console.log("data stream open " + clientID);
      };
      channel.onclose = function(event) {
        delete _this.dataChannels[clientID];
        return console.log("data stream close " + clientID);
      };
      channel.onmessage = function(message) {
        console.log("data stream message " + clientID);
        return console.log(message);
      };
      channel.onerror = function(err) {
        return console.log("data stream error " + clientID + ": " + err);
      };
      this.dataChannels[clientID] = channel;
      return channel;
    };

    WebRTC.prototype.sendEvent = function(eventName, data) {
      var dataChannel, _i, _len, _ref, _results;

      _ref = this.dataChannels;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        dataChannel = _ref[_i];
        _results.push(dataChannel.send(JSON.stringify({
          "eventName": eventName,
          "data": data
        })));
      }
      return _results;
    };

    return WebRTC;

  })();

}).call(this);
