''' Handles all frontend setup for UI.
'''

class window.AppView extends Backbone.View
  el: "#client-server"

  initialize: (options)->
    @serverFileCollection = options.serverFileCollection
    @routeCollection = options.routeCollection
    @userDatabase = options.userDatabase
    serverAge = new ServerAge($(".server-age-wrapper"))

    @tmplEditPage = Handlebars.templates["edit-page"]
    @tmplDatabasePage = Handlebars.templates["database-page"]
    @tmplTopbarButtons = Handlebars.templates["topbar-buttons"]
    @tmplServerIDMessage = Handlebars.templates["server-id-message"]

    @on("setServerID", @setClientBrowserLink)
    @on("onUnavailableID", @goToUnavailableIDPage)
    @on("onInvalidID", @goToInvalidIDPage)

  setClientBrowserLink: (serverID) =>
    @goToEditPage()
    link = window.location.origin + "/connect/" + serverID + "/"
    @clientBrowserLink.attr("href", link)

  renderTopbarButtons: =>
    $(".topbar").append(@tmplTopbarButtons)
    @clientBrowserLink = $(".navbar .browse")
    @archiveButton = $(".navbar .archive")
    @editLink = $(".navbar .edit")
    @databaseLink = $(".navbar .database")

    @editLink.click(@goToEditPage)
    @databaseLink.click(@goToDatabasePage)

  goToEditPage: =>
    @renderTopbarButtons()
    $(@el).html(@tmplEditPage)

    @serverFileCollectionView = new ClientServerCollectionView(
      serverFileCollection: @serverFileCollection,
      routeCollection: @routeCollection,
      userDatabase: @userDatabase)

    @archiver = new ClientServerArchiver(
      serverFileCollection: @serverFileCollection,
      routeCollection: @routeCollection,
      userDatabase: @userDatabase,
      button: @archiveButton)

  goToDatabasePage: =>
    @renderTopbarButtons()
    $(@el).html(@tmplDatabasePage())

    @databaseView = new DatabaseView(userDatabase: @userDatabase)

  goToUnavailableIDPage: (desiredServerID) =>
    $(".topbar-buttons").remove()
    $(@el).html(@tmplServerIDMessage(
      message: "\"" + desiredServerID + "\" is unavailable.",
      alternativeServerID: @getAlternativeServerID()))

  goToInvalidIDPage: (desiredServerID) =>
    $(".topbar-buttons").remove()
    $(@el).html(@tmplServerIDMessage(
      message: "\"" + desiredServerID + "\" is an invalid server name.",
      alternativeServerID: @getAlternativeServerID()))

  getAlternativeServerID: =>
    randomIndex = Math.floor(Math.random() * AppView.listOfDogBreeds.length)
    return AppView.listOfDogBreeds[randomIndex]

  @listOfDogBreeds: [
    "AfghanHound",
    "Aidi",
    "AiredaleTerrier",
    "AkbashDog",
    "AkitaInu",
    "AlanoEspanol",
    "AlaskanKlee",
    "AlaskanMalamute",
    "AlpineDachsbracke",
    "AlpineSpaniel",
    "AmericanAkita",
    "AmericanBulldog",
    "AmericanCocker",
    "AmericanEskimo",
    "AmericanFoxhound",
    "AmericanHairless",
    "AmericanMastiff",
    "AmericanPit",
    "AmericanStaffordshire",
    "AmericanWater",
    "AnatolianShepherd",
    "AngloFrancaisde",
    "AppenzellerSennenhund",
    "AriegePointer",
    "Ariegeois",
    "Armant",
    "ArmenianGampr",
    "ArtoisHound",
    "AustralianCattle",
    "AustralianKelpie",
    "AustralianShepherd",
    "AustralianSilky",
    "AustralianStumpy",
    "AustralianTerrier",
    "AustrianBlack",
    "AustrianPinscher",
    "Azawakh",
    "Barbet",
    "Basenji",
    "BasqueShepherd",
    "BassetArtesien",
    "BassetBleu",
    "BassetFauve",
    "GrandBasset",
    "PetitBasset",
    "BassetHound",
    "BavarianMountain",
    "Beagle",
    "BeagleHarrier",
    "BeardedCollie",
    "Beauceron",
    "BedlingtonTerrier",
    "BelgianShepherd",
    "BelgianShepherd",
    "BelgianShepherd",
    "BelgianShepherd",
    "BergamascoShepherd",
    "BergerBlanc",
    "BergerPicard",
    "BernerLaufhund",
    "BerneseMountain",
    "BichonFrise",
    "Billy",
    "Blackand",
    "Blackand",
    "Bullenbeisser",
    "BlackNorwegian",
    "BlackRussian",
    "BlackmouthCur",
    "GrandBleu",
    "PetitBleu",
    "Bloodhound",
    "BlueLacy",
    "BluePaul",
    "BluetickCoonhound",
    "Boerboel",
    "BohemianShepherd",
    "Bolognese",
    "BorderCollie",
    "BorderTerrier",
    "Borzoi",
    "BosnianCoarsehaired",
    "BostonTerrier",
    "Bouvierdes",
    "Bouvierdes",
    "Boxer",
    "BoykinSpaniel",
    "BraccoItaliano",
    "BraquedAuvergne",
    "Braquedu",
    "Braquedu",
    "BraqueFrancais",
    "BraqueSaintGermain",
    "BrazilianTerrier",
    "Briard",
    "BriquetGriffon",
    "Brittany",
    "Broholmer",
    "BrunoJura",
    "BucovinaShepherd",
    "Bulland",
    "BullTerrier",
    "BullTerrier",
    "Bulldog",
    "Bullmastiff",
    "BullyKutta",
    "BurgosPointer",
    "CanaanDog",
    "CanadianEskimo",
    "CaneCorso",
    "Caoda",
    "Caode",
    "CaoFila",
    "CarolinaDog",
    "CarpathianShepherd",
    "CatahoulaCur",
    "CatalanSheepdog",
    "CaucasianShepherd",
    "CavalierKing",
    "CentralAsian",
    "CeskyFousek",
    "CeskyTerrier",
    "ChesapeakeBay",
    "ChienFrancais",
    "Chiengris",
    "Chihuahua",
    "ChileanFox",
    "ChineseChongqing",
    "ChineseCrested",
    "ChineseImperial",
    "Chinook",
    "Chippiparai",
    "ChowChow",
    "CiernySery",
    "CimarronUruguayo",
    "CirnecodellEtna",
    "ClumberSpaniel",
    "RoughCollie",
    "SmoothCollie",
    "Combai",
    "CordobaFighting",
    "Cotonde",
    "CretanHound",
    "CroatianSheepdog",
    "CumberlandSheepdog",
    "CurlyCoated",
    "Cursinu",
    "CzechoslovakWolfdog",
    "Dalmatian",
    "DandieDinmont",
    "DanishSwedish",
    "DeutscheBracke",
    "DobermanPinscher",
    "DogoArgentino",
    "DogoCubano",
    "Doguede",
    "DrentsePatrijshond",
    "Drever",
    "Dunker",
    "DutchShepherd",
    "DutchSmoushond",
    "EastEuropeanShepherd",
    "Elo",
    "EnglishCocker",
    "EnglishCoonhound",
    "EnglishFoxhound",
    "EnglishMastiff",
    "EnglishSetter",
    "EnglishShepherd",
    "EnglishSpringer",
    "EnglishToy",
    "EnglishWater",
    "EnglishWhite",
    "EntlebucherMountain",
    "EpagneulBleu",
    "EstonianHound",
    "EstrelaMountain",
    "Eurasier",
    "FilaBrasileiro",
    "FinnishHound",
    "FinnishLapphund",
    "FinnishSpitz",
    "FlatCoatedRetriever",
    "FormosanMountain",
    "FoxTerrier",
    "WireFox",
    "FrenchBrittany",
    "FrenchBulldog",
    "FrenchSpaniel",
    "GasconSaintongeois",
    "Georgianshepherd",
    "GermanLonghaired",
    "GermanPinscher",
    "GermanRoughhaired",
    "GermanShepherd",
    "GermanShorthaired",
    "GermanSpaniel",
    "GermanSpitz",
    "GermanWirehaired",
    "GiantSchnauzer",
    "Glenof",
    "GoldenRetriever",
    "GordonSetter",
    "GranMastin",
    "GrandAngloFrancais",
    "GrandGriffon",
    "GreatDane",
    "GreatPyrenees",
    "GreaterSwiss",
    "GreekHarehound",
    "GreenlandDog",
    "Greyhound",
    "GriffonBleu",
    "GriffonBruxellois",
    "GriffonFauve",
    "GriffonNivernais",
    "HanoverHound",
    "HareIndian",
    "Harrier",
    "Havanese",
    "HawaiianPoi",
    "HimalayanSheepdog",
    "Hokkaido",
    "HortayaBorzaya",
    "Hovawart",
    "HungarianHound",
    "Huntaway",
    "Hygenhund",
    "IcelandicSheepdog",
    "IndianSpitz",
    "IrishRed",
    "IrishSetter",
    "IrishTerrier",
    "IrishWater",
    "IrishWolfhound",
    "IstrianCoarsehaired",
    "IstrianShorthaired",
    "ItalianGreyhound",
    "Jagdterrier",
    "Jamthund",
    "JapaneseChin",
    "JapaneseSpitz",
    "JapaneseTerrier",
    "KaiKen",
    "KangalDog",
    "Kanni",
    "KarakachanDog",
    "KarelianBear",
    "KarstShepherd",
    "Keeshond",
    "KerryBeagle",
    "KerryBlue",
    "KingCharles",
    "KingShepherd",
    "Kintamani",
    "Kishu",
    "Komondor",
    "Kooikerhondje",
    "Koolie",
    "KoreanJindo",
    "Kromfohrlander",
    "KunmingWolfdog",
    "Kuri",
    "Kuvasz",
    "KyiLeo",
    "LabradorRetriever",
    "LagottoRomagnolo",
    "LakelandTerrier",
    "LancashireHeeler",
    "Landseer",
    "LapponianHerder",
    "Leonberger",
    "LhasaApso",
    "LithuanianHound",
    "LonghairedWhippet",
    "Lowchen",
    "Maltese",
    "ManchesterTerrier",
    "MaremmaSheepdog",
    "McNab",
    "MexicanHairless",
    "MiniatureAustralian",
    "MiniatureAmerican",
    "MiniatureFox",
    "MiniaturePinscher",
    "MiniatureSchnauzer",
    "Mioritic",
    "Molossus",
    "MontenegrinMountain",
    "MoscowWatchdog",
    "MoscowWater",
    "MountainCur",
    "Mucuchies",
    "MudholHound",
    "Mudi",
    "LargeMunsterlander",
    "SmallMunsterlander",
    "Newfoundland",
    "NewZealand",
    "NorfolkSpaniel",
    "NorfolkTerrier",
    "Norrbottenspets",
    "NorthCountry",
    "NorthernInuit",
    "NorwegianBuhund",
    "NorwegianElkhound",
    "NorwegianLundehund",
    "NorwichTerrier",
    "NovaScotia",
    "OldDanish",
    "OldEnglish",
    "OldGerman",
    "Oldtime",
    "OldeEnglish",
    "Otterhound",
    "PaisleyTerrier",
    "Papillon",
    "ParsonRussell",
    "PatterdaleTerrier",
    "Pekingese",
    "Perrode",
    "Perrode",
    "PeruvianHairless",
    "Phalene",
    "PharaohHound",
    "PhuQuoc",
    "PicardySpaniel",
    "PlottHound",
    "PodencoCanario",
    "Pointer",
    "PolishGreyhound",
    "PolishHound",
    "PolishHunting",
    "PolishLowland",
    "PolishTatra",
    "Pomeranian",
    "PontAudemerSpaniel",
    "Poodle",
    "Porcelaine",
    "PortuguesePodengo",
    "PortuguesePointer",
    "PortugueseWater",
    "PosavacHound",
    "PrazskyKrysarik",
    "Pudelpointer",
    "Pug",
    "Puli",
    "Pumi",
    "PungsanDog",
    "PyreneanMastiff",
    "PyreneanShepherd",
    "Rajapalayam",
    "RampurGreyhound",
    "RastreadorBrasileiro",
    "RatoneroBodeguero",
    "RatoneroValenciano",
    "RatTerrier",
    "RedboneCoonhound",
    "RhodesianRidgeback",
    "Rottweiler",
    "RussianSpaniel",
    "RussianToy",
    "Russiantracker",
    "RussoEuropeanLaika",
    "RussellTerrier",
    "SabuesoEspanol",
    "SaintUsugeSpaniel",
    "SakhalinHusky",
    "Saluki",
    "Samoyed",
    "Sapsali",
    "Šarplaninac",
    "Schapendoes",
    "Schillerstövare",
    "Schipperke",
    "StandardSchnauzer",
    "SchweizerLaufhund",
    "SchweizerischerNiederlaufhund",
    "ScotchCollie",
    "ScottishDeerhound",
    "ScottishTerrier",
    "SealyhamTerrier",
    "SegugioItaliano",
    "SeppalaSiberian",
    "SerbianHound",
    "SerbianTricolour",
    "SharPei",
    "ShetlandSheepdog",
    "ShibaInu",
    "ShihTzu",
    "Shikoku",
    "ShilohShepherd",
    "SiberianHusky",
    "SilkenWindhound",
    "SinhalaHound",
    "SkyeTerrier",
    "Sloughi",
    "SlovakCuvac",
    "SlovakianRoughhaired",
    "SlovenskKopov",
    "Smalandsstovare",
    "SmallGreek",
    "SoftCoatedWheaten",
    "SouthRussian",
    "SouthernHound",
    "SpanishMastiff",
    "SpanishWater",
    "SpinoneItaliano",
    "SportingLucas",
    "StBernard",
    "StJohns",
    "Stabyhoun",
    "StaffordshireBull",
    "StephensCur",
    "StyrianCoarsehaired",
    "SussexSpaniel",
    "SwedishLapphund",
    "SwedishVallhund",
    "Taigan",
    "Talbot",
    "TamaskanDog",
    "TeddyRoosevelt",
    "Telomian",
    "TennesseeTreeing",
    "TenterfieldTerrier",
    "ThaiBangkaew",
    "ThaiRidgeback",
    "TibetanMastiff",
    "TibetanSpaniel",
    "TibetanTerrier",
    "Tornjak",
    "Tosa",
    "ToyBulldog",
    "ToyFox",
    "ToyManchester",
    "ToyTrawler",
    "TransylvanianHound",
    "TreeingCur",
    "TreeingWalker",
    "TriggHound",
    "TweedWater",
    "TyroleanHound",
    "VolpinoItaliano",
    "CardiganWelsh",
    "PembrokeWelsh",
    "WelshSheepdog",
    "WelshSpringer",
    "WelshTerrier",
    "WestHighland",
    "WestSiberian",
    "WestphalianDachsbracke",
    "Wetterhoun",
    "Whippet",
    "WhiteShepherd",
    "WirehairedPointing",
    "WirehairedVizsla"
  ]
