// Generated by CoffeeScript 1.6.2
(function() {
  ' Handles all frontend setup for UI.';
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.AppView = (function(_super) {
    __extends(AppView, _super);

    function AppView() {
      this.setClientBrowserLink = __bind(this.setClientBrowserLink, this);      _ref = AppView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AppView.prototype.el = "#client-server";

    AppView.prototype.initialize = function() {
      return this.serverFileCollectionView = new ServerFileCollectionView({
        collection: this.collection
      });
    };

    AppView.prototype.setClientBrowserLink = function(link) {
      var clientBrowserLink;

      clientBrowserLink = $(".browser-link");
      clientBrowserLink.attr('href', link);
      return clientBrowserLink.html(link);
    };

    return AppView;

  })(Backbone.View);

}).call(this);
