// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ClientServerDataChannel = (function(_super) {
    __extends(ClientServerDataChannel, _super);

    function ClientServerDataChannel(options) {
      this.onConnection = __bind(this.onConnection, this);
      this.onOpen = __bind(this.onOpen, this);
      this.onConnectionCallback = options.onConnectionCallback;
      this.onDataCallback = options.onDataCallback;
      this.onReady = options.onReady;
      this.onConnectionCloseCallback = options.onConnectionCloseCallback;
      this.id = options.desiredServerID;
      this.onUnavailableID = options.onUnavailableIDCallback;
      this.onInvalidID = options.onInvalidIDCallback;
      ClientServerDataChannel.__super__.constructor.call(this, this.onDataCallback);
      this.peer.on("connection", this.onConnection);
    }

    ClientServerDataChannel.prototype.onOpen = function(id) {
      ClientServerDataChannel.__super__.onOpen.call(this, id);
      return this.onReady();
    };

    ClientServerDataChannel.prototype.onConnection = function(connection) {
      var _this = this;
      connection.on("open", function() {
        return _this.onConnectionCallback(connection);
      });
      connection.on("data", this.onData);
      return connection.on("close", function() {
        return _this.onConnectionCloseCallback(connection);
      });
    };

    return ClientServerDataChannel;

  })(ClientDataChannel);

}).call(this);
