// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.ClientServerArchiver = (function() {
    function ClientServerArchiver(params) {
      this.archive = __bind(this.archive, this);      this.serverFileCollection = params.serverFileCollection;
      this.routeCollection = params.routeCollection;
      this.userDatabase = params.userDatabase;
      this.button = params.button;
      this.button.click(this.archive);
    }

    ClientServerArchiver.prototype.archive = function() {
      var content, developmentFolder, productionFolder, zip,
        _this = this;

      zip = new JSZip();
      productionFolder = zip.folder("live_version");
      developmentFolder = zip.folder("edited_version");
      this.serverFileCollection.each(function(serverFile) {
        var folder;

        if (serverFile.get("isProductionVersion")) {
          folder = productionFolder;
        } else {
          folder = developmentFolder;
        }
        return folder.file(serverFile.get("name"), serverFile.get("contents"));
      });
      this.routeCollection.each(function(route) {
        var contents, folder;

        if (route.get("isProductionVersion")) {
          folder = productionFolder;
        } else {
          folder = developmentFolder;
        }
        contents = {};
        contents.routePath = route.get("routePath");
        contents.routeCode = route.get("routeCode");
        return folder.file(route.get("name") + ".route.js", JSON.stringify(contents, null, " "));
      });
      zip.file("database.db", this.userDatabase.toString());
      content = zip.generate();
      return location.href = "data:application/zip;base64," + content;
    };

    return ClientServerArchiver;

  })();

}).call(this);

/*
//@ sourceMappingURL=ClientServerArchiver.map
*/
