// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    _this = this;

  window.Route = (function(_super) {

    __extends(Route, _super);

    function Route() {
      return Route.__super__.constructor.apply(this, arguments);
    }

    Route.prototype.defaults = {
      routePath: "",
      routeCode: "",
      options: {},
      isRequired: false,
      isProductionVersion: false
    };

    Route.prototype.initialize = function() {};

    return Route;

  })(Backbone.Model);

  window.RouteCollection = (function(_super) {

    __extends(RouteCollection, _super);

    function RouteCollection() {
      var _this = this;
      this.getRouteCode = function(routePath) {
        return RouteCollection.prototype.getRouteCode.apply(_this, arguments);
      };
      this.hasRoute = function(routePath) {
        return RouteCollection.prototype.hasRoute.apply(_this, arguments);
      };
      this.comparator = function(route) {
        return RouteCollection.prototype.comparator.apply(_this, arguments);
      };
      return RouteCollection.__super__.constructor.apply(this, arguments);
    }

    RouteCollection.prototype.model = Route;

    RouteCollection.prototype.initialize = function() {
      var indexRoute;
      indexRoute = new Route({
        routePath: "/test",
        routeCode: "'test page: ' + params.q",
        isRequired: true
      });
      return this.add(indexRoute);
    };

    RouteCollection.prototype.comparator = function(route) {
      return route.get("routePath");
    };

    RouteCollection.prototype.hasRoute = function(routePath) {
      console.log("route path: " + routePath);
      return this.findWhere({
        routePath: routePath
      });
    };

    RouteCollection.prototype.getRouteCode = function(routePath) {
      return this.findWhere({
        routePath: routePath
      }).get("routeCode");
    };

    return RouteCollection;

  })(Backbone.Collection);

}).call(this);
