// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    var appView, serverFileCollection;
    serverFileCollection = new ServerFileCollection();
    appView = new AppView({
      collection: serverFileCollection
    });
    return window.webRTC = new WebRTC(serverFileCollection, appView.setClientBrowserLink);
  });

}).call(this);
