// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    var appView, clientServer, routeCollection, serverFileCollection;
    serverFileCollection = new ServerFileCollection();
    routeCollection = new RouteCollection();
    appView = new AppView({
      serverFileCollection: serverFileCollection,
      routeCollection: routeCollection
    });
    return clientServer = new ClientServer(serverFileCollection, routeCollection, appView);
  });

}).call(this);
