// Generated by CoffeeScript 1.6.1
(function() {
  'View of a single file in the editor (depends on js/img/css etc)';
  var _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ServerFileView = (function(_super) {

    __extends(ServerFileView, _super);

    function ServerFileView() {
      var _this = this;
      this.updateContents = function() {
        return ServerFileView.prototype.updateContents.apply(_this, arguments);
      };
      this.renderAsImage = function() {
        return ServerFileView.prototype.renderAsImage.apply(_this, arguments);
      };
      this.renderAsSourceCode = function() {
        return ServerFileView.prototype.renderAsSourceCode.apply(_this, arguments);
      };
      this.render = function() {
        return ServerFileView.prototype.render.apply(_this, arguments);
      };
      return ServerFileView.__super__.constructor.apply(this, arguments);
    }

    ServerFileView.prototype.initialize = function(options) {
      this.tplSourceCode = Handlebars.compile($("#source-code-template").html());
      return this.tplImage = Handlebars.compile($("#image-template").html());
    };

    ServerFileView.prototype.render = function() {
      if (this.model.get("fileType") !== ServerFile.fileTypeEnum.IMG) {
        this.renderAsSourceCode();
      } else {
        this.renderAsImage();
      }
      return this;
    };

    ServerFileView.prototype.renderAsSourceCode = function() {
      var editorMode, fileContents;
      $(this.el).html(this.tplSourceCode);
      fileContents = $(this.el).find(".file-contents");
      fileContents.text(this.model.get("contents"));
      this.aceEditor = ace.edit(fileContents[0]);
      this.aceEditor.setTheme("ace/theme/tomorrow_night_eighties");
      this.aceEditor.setFontSize("12px");
      editorMode = "ace/mode/html";
      switch (this.model.get("fileType")) {
        case ServerFile.fileTypeEnum.CSS:
          editorMode = "ace/mode/css";
          break;
        case ServerFile.fileTypeEnum.JS:
        case ServerFile.fileTypeEnum.DYNAMIC:
          editorMode = "ace/mode/javascript";
      }
      this.aceEditor.getSession().setMode(editorMode);
      return this.aceEditor.on("change", this.updateContents);
    };

    ServerFileView.prototype.renderAsImage = function() {
      $(this.el).html(this.tplImage);
      return this.$("img").attr("src", this.model.get("contents"));
    };

    ServerFileView.prototype.updateContents = function() {
      return this.model.save("contents", this.aceEditor.getValue());
    };

    return ServerFileView;

  })(Backbone.View);

}).call(this);
