// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.ServerAge = (function() {
    function ServerAge(elem) {
      var ONE_DAY, ONE_HOUR, ONE_MINUTE, ONE_SECOND, ONE_WEEK, start, timeElem,
        _this = this;

      this.elem = elem;
      this.convertToString = __bind(this.convertToString, this);
      ONE_SECOND = 1000;
      ONE_MINUTE = ONE_SECOND * 60;
      ONE_HOUR = ONE_MINUTE * 60;
      ONE_DAY = ONE_HOUR * 24;
      ONE_WEEK = ONE_DAY * 7;
      timeElem = this.elem.find(".server-age");
      timeElem.html("0 minutes");
      start = (new Date()).getTime();
      setInterval(function() {
        var curr, days, diff, first, hours, minutes, time, weeks;

        curr = (new Date()).getTime();
        diff = curr - start;
        time = "";
        first = true;
        weeks = Math.floor(diff / ONE_WEEK);
        time += _this.convertToString(weeks, "week", first);
        diff = diff - (weeks * ONE_WEEK);
        first = first ? weeks < 1 : false;
        days = Math.floor(diff / ONE_DAY);
        time += _this.convertToString(days, "day", first);
        diff = diff - (days * ONE_DAY);
        first = first ? days < 1 : false;
        hours = Math.floor(diff / ONE_HOUR);
        time += _this.convertToString(hours, "hour", first);
        diff = diff - (hours * ONE_HOUR);
        first = first ? hours < 1 : false;
        minutes = Math.floor(diff / ONE_MINUTE);
        time += _this.convertToString(minutes, "minute", first);
        return timeElem.html(time);
      }, ONE_MINUTE);
    }

    ServerAge.prototype.convertToString = function(number, name, first) {
      var start;

      if (number < 1) {
        return "";
      }
      if (number > 1) {
        name += "s";
      }
      start = !first ? ", " : "";
      return start + number + " " + name;
    };

    return ServerAge;

  })();

}).call(this);
