// Generated by CoffeeScript 1.6.1
(function() {
  var _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ServerFile = (function(_super) {

    __extends(ServerFile, _super);

    function ServerFile() {
      var _this = this;
      this.rawTypeToFileType = function(rawType) {
        return ServerFile.prototype.rawTypeToFileType.apply(_this, arguments);
      };
      this.updateFileType = function() {
        return ServerFile.prototype.updateFileType.apply(_this, arguments);
      };
      return ServerFile.__super__.constructor.apply(this, arguments);
    }

    ServerFile.prototype.defaults = {
      name: "",
      size: 0,
      contents: "",
      type: "",
      fileType: "",
      isLandingPage: false,
      isProductionVersion: false
    };

    ServerFile.prototype.fileTypeEnum = {
      HTML: "HTML",
      CSS: "CSS",
      JS: "JS",
      IMG: "IMG",
      NONE: "NONE"
    };

    ServerFile.prototype.initialize = function() {
      this.on("change:type", this.updateFileType);
      return this.updateFileType();
    };

    ServerFile.prototype.updateFileType = function() {
      return this.set("fileType", this.rawTypeToFileType(this.get("type")));
    };

    ServerFile.prototype.rawTypeToFileType = function(rawType) {
      if (rawType === "image/jpeg" || rawType === "image/png") {
        return this.fileTypeEnum.IMG;
      }
      if (rawType === "text/html") {
        return this.fileTypeEnum.HTML;
      }
      if (rawType === "text/css") {
        return this.fileTypeEnum.CSS;
      }
      if (rawType === "application/x-javascript") {
        return this.fileTypeEnum.JS;
      }
      return this.fileTypeEnum.NONE;
    };

    return ServerFile;

  })(Backbone.Model);

}).call(this);
