// Generated by CoffeeScript 1.6.2
(function() {
  ' Backend and view for data surrounding the connections to the server. \n\nTracks the count.';
  var _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ServerConnectionDataModel = (function(_super) {
    __extends(ServerConnectionDataModel, _super);

    function ServerConnectionDataModel() {
      _ref = ServerConnectionDataModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ServerConnectionDataModel.prototype.defaults = {
      count: 0
    };

    return ServerConnectionDataModel;

  })(Backbone.Model);

  window.ServerConnectionDataView = (function(_super) {
    __extends(ServerConnectionDataView, _super);

    function ServerConnectionDataView() {
      _ref1 = ServerConnectionDataView.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    ServerConnectionDataView.prototype.initialize = function(options) {
      var _this = this;

      this.el = $(this.el);
      this.dataEl = this.el.find(".server-connection-data");
      this.dataEl.html(this.model.get("count"));
      return this.model.on("change:count", function(newCount) {
        return _this.dataEl.html(_this.model.get("count"));
      });
    };

    return ServerConnectionDataView;

  })(Backbone.View);

}).call(this);
