// Generated by CoffeeScript 1.6.2
(function() {
  'Simple wrapper for rendering a user-created Handlebars template.\n\nCould be built out in the future by supporting user-created handlebars helpers, etc.';  window.UserTemplateRenderer = (function() {
    function UserTemplateRenderer() {}

    UserTemplateRenderer.renderTemplate = function(source, context) {
      var template;

      template = Handlebars.compile(source);
      return template(context);
    };

    return UserTemplateRenderer;

  }).call(this);

}).call(this);
