// Generated by CoffeeScript 1.6.2
(function() {
  window.UserDatabase = (function() {
    function UserDatabase() {
      this.database = TAFFY();
    }

    return UserDatabase;

  })();

}).call(this);
