// Generated by CoffeeScript 1.6.2
(function() {
  'Simple wrapper for user sessions.';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.UserSessions = (function() {
    function UserSessions() {
      this.getSession = __bind(this.getSession, this);
      this.removeSession = __bind(this.removeSession, this);
      this.addSession = __bind(this.addSession, this);      this.sessions = {};
      console.log("sessions initialized");
      this.randomVal = CryptoJS.lib.WordArray.random(128 / 8);
      this.hash = CryptoJS.SHA256;
    }

    UserSessions.prototype.addSession = function(sessionId) {
      return this.sessions[this.hash(sessionId + "" + this.randomVal)] = {};
    };

    UserSessions.prototype.removeSession = function(sessionId) {
      return delete this.sessions[this.hash(sessionId + "" + this.randomVal)];
    };

    UserSessions.prototype.getSession = function(sessionId) {
      return this.sessions[this.hash(sessionId + "" + this.randomVal)];
    };

    return UserSessions;

  })();

}).call(this);
