// Generated by CoffeeScript 1.6.2
(function() {
  'Simple wrapper for a taffy database. \n\nMight be extended to back up the database to local storage, a zip file, etc.';  window.UserDatabase = (function() {
    function UserDatabase() {
      this.database = TAFFY();
    }

    return UserDatabase;

  })();

}).call(this);
