// Generated by CoffeeScript 1.6.2
(function() {
  'Simple wrapper for a taffy database. \n\nMight be extended to back up the database to local storage, a zip file, etc.';
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.UserDatabase = (function() {
    function UserDatabase() {
      this.clear = __bind(this.clear, this);
      this.runQuery = __bind(this.runQuery, this);
      this.fromJSONArray = __bind(this.fromJSONArray, this);
      this.toString = __bind(this.toString, this);
      this.initLocalStorage = __bind(this.initLocalStorage, this);      this.database = TAFFY();
    }

    UserDatabase.prototype.initLocalStorage = function(namespace) {
      return this.database.store(namespace + "-UserDatabase");
    };

    UserDatabase.prototype.toString = function(pretty) {
      if (pretty) {
        return JSON.stringify(this.database().get(), null, 4);
      }
      return this.database().stringify();
    };

    UserDatabase.prototype.fromJSONArray = function(array) {
      return this.database.insert(array);
    };

    UserDatabase.prototype.runQuery = function(query) {
      var code;

      code = "(function(db) { " + query + " }).call(null, this.database)";
      return eval(code);
    };

    UserDatabase.prototype.clear = function() {
      return this.database().remove();
    };

    return UserDatabase;

  })();

}).call(this);
